### PR TITLE
Draft PR of AddLoan Command

### PR DESCRIPTION
**Pull request by troomtroom**
Only a draft, Tests don't pass yet.

### CODE REVIEW

**Comment by nexolute** [comment]
I am seeing a lot of issues with this PR even if it pass Travis. I highly recommend you to redo the PR from a new branch instead of continuing from here. Here are some comments:

- You are committing the class files. I believe you got that because you are not following the instructions for building using Gradle task. Please remove it.
- You are modifying the files that are not relevant to your part. For instance, you added a new line for `AddBudgetCommandParser`. Please remove that to make the I commits and git blame clean.
- You are committing files with pure comments. In general, you should not have any dummy files. Please remove it if you are not using them. I highly doubt you will be able to finish those features by Monday.

**Comment by troomtroom** [comment]
Removed all excess files, does this suffice?

I see what I did wrong there.

**Comment by nexolute** [comment]
I think I am okay with merging this.

For future PR, please work on writing better commit messages. For example, I am worried for a moment when you write `Remove .gitignore` for c2a3824. Turns out you are just removing a line from it.

**Comment by troomtroom** [comment]
> I think I am okay with merging this.
> 
> For future PR, please work on writing better commit messages. For example, I am worried for a moment when you write `Remove .gitignore` for [c2a3824](https://github.com/AY1920S1-CS2103T-W12-4/main/commit/c2a3824f0be932cdca4a8e0fa126f12b7989198e). Turns out you are just removing a line from it.

Ill avoid vague commit messages, thanks!

**Pull request merged**
