### PR TITLE
Implement basic model for transaction

### PR DESCRIPTION
**Pull request by weiyang13**
Far from ready, but here's a draft PR. Feel free to make comments while I implement

### CODE REVIEW

**Comment by weiyang13** [comment]
Note on Amount implementation:

Adapted from Phone, which stores the value as a String.

I do recognize the need for:

1) Standardization of format in GUI as '<dollars>.<cents>'
1) Convenient computation for budgeting

In light of this, I will likely change the implementation in the near future

**Comment by nexolute** [comment]
I am rather concern about the computation of amount too. Why not we use `double`, then implement `toString` to make it return in the right format?

**Comment by weiyang13** [comment]
@nexolute Yes I agree. In fact I'm thinking of using `long` to avoid the precision issues that may arise with `double`. Also, I'll add in a '$' character for `toString()`.

**Comment by nexolute** [comment]
Okay, I supposed you are going to provide the necessary arithmetic functions too?

**Comment by weiyang13** [comment]
@nexolute Definitely! But I may need inputs from other users before I decide on the methods.

**Comment by weiyang13** [comment]
@nexolute I have implemented a rudimentary transaction class. It does not even have a date but please accept this first if there are no serious errors. If coverage is blocking the merging please weaken or disable unless you feel I should implement tests at this stage.

**Comment by nexolute** [comment]
I have increased the coverage decrease threshold for failure to 10% at this point of the project. I'll review your PR shortly.

**Pull request merged**
